version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile        # <-- root-level, Python app
    container_name: empathai-backend
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile        # <-- frontend/React build
    container_name: empathai-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
