version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile        # <-- root-level, Python app
    container_name: empathai-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: empathai-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend
    restart: unless-stopped

  # Production frontend service (uncomment to use)
  # frontend-prod:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #     target: production
  #   container_name: empathai-frontend-prod
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped